# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_condition.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(863, 565)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.actor_lineEdit = QtWidgets.QLineEdit(Form)
        self.actor_lineEdit.setObjectName("actor_lineEdit")
        self.horizontalLayout_7.addWidget(self.actor_lineEdit)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.huo_actor_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.huo_actor_radioButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.huo_actor_radioButton.setChecked(True)
        self.huo_actor_radioButton.setObjectName("huo_actor_radioButton")
        self.horizontalLayout.addWidget(self.huo_actor_radioButton)
        self.qie_actor_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.qie_actor_radioButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.qie_actor_radioButton.setObjectName("qie_actor_radioButton")
        self.horizontalLayout.addWidget(self.qie_actor_radioButton)
        self.horizontalLayout_7.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.actor_scrollArea = QtWidgets.QScrollArea(Form)
        self.actor_scrollArea.setWidgetResizable(True)
        self.actor_scrollArea.setObjectName("actor_scrollArea")
        self.actor_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.actor_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 261, 466))
        self.actor_scrollAreaWidgetContents.setObjectName("actor_scrollAreaWidgetContents")
        self.actor_scrollArea.setWidget(self.actor_scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.actor_scrollArea)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.custom_tag_lineEdit = QtWidgets.QLineEdit(Form)
        self.custom_tag_lineEdit.setText("")
        self.custom_tag_lineEdit.setObjectName("custom_tag_lineEdit")
        self.horizontalLayout_2.addWidget(self.custom_tag_lineEdit)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.huo_tag_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.huo_tag_radioButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.huo_tag_radioButton.setChecked(True)
        self.huo_tag_radioButton.setObjectName("huo_tag_radioButton")
        self.horizontalLayout_5.addWidget(self.huo_tag_radioButton)
        self.qie_tag_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.qie_tag_radioButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.qie_tag_radioButton.setObjectName("qie_tag_radioButton")
        self.horizontalLayout_5.addWidget(self.qie_tag_radioButton)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.custom_tag_scrollArea = QtWidgets.QScrollArea(Form)
        self.custom_tag_scrollArea.setWidgetResizable(True)
        self.custom_tag_scrollArea.setObjectName("custom_tag_scrollArea")
        self.custom_tag_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.custom_tag_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 297, 466))
        self.custom_tag_scrollAreaWidgetContents.setObjectName("custom_tag_scrollAreaWidgetContents")
        self.custom_tag_scrollArea.setWidget(self.custom_tag_scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.custom_tag_scrollArea)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.series_lineEdit = QtWidgets.QLineEdit(Form)
        self.series_lineEdit.setObjectName("series_lineEdit")
        self.horizontalLayout_3.addWidget(self.series_lineEdit)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.huo_series_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.huo_series_radioButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.huo_series_radioButton.setChecked(True)
        self.huo_series_radioButton.setObjectName("huo_series_radioButton")
        self.horizontalLayout_6.addWidget(self.huo_series_radioButton)
        self.qie_series_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.qie_series_radioButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.qie_series_radioButton.setObjectName("qie_series_radioButton")
        self.horizontalLayout_6.addWidget(self.qie_series_radioButton)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.serise_scrollArea = QtWidgets.QScrollArea(Form)
        self.serise_scrollArea.setWidgetResizable(True)
        self.serise_scrollArea.setObjectName("serise_scrollArea")
        self.series_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.series_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 261, 466))
        self.series_scrollAreaWidgetContents.setObjectName("series_scrollAreaWidgetContents")
        self.serise_scrollArea.setWidget(self.series_scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.serise_scrollArea)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.confirm_pushButton = QtWidgets.QPushButton(Form)
        self.confirm_pushButton.setObjectName("confirm_pushButton")
        self.horizontalLayout_4.addWidget(self.confirm_pushButton)
        self.cancle_pushButton = QtWidgets.QPushButton(Form)
        self.cancle_pushButton.setObjectName("cancle_pushButton")
        self.horizontalLayout_4.addWidget(self.cancle_pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "演员"))
        self.actor_lineEdit.setPlaceholderText(_translate("Form", "筛选词"))
        self.huo_actor_radioButton.setText(_translate("Form", "或"))
        self.qie_actor_radioButton.setText(_translate("Form", "且"))
        self.label_2.setText(_translate("Form", "自定义标签"))
        self.custom_tag_lineEdit.setPlaceholderText(_translate("Form", "筛选词"))
        self.huo_tag_radioButton.setText(_translate("Form", "或"))
        self.qie_tag_radioButton.setText(_translate("Form", "且"))
        self.label_3.setText(_translate("Form", "系列"))
        self.series_lineEdit.setPlaceholderText(_translate("Form", "筛选词"))
        self.huo_series_radioButton.setText(_translate("Form", "或"))
        self.qie_series_radioButton.setText(_translate("Form", "且"))
        self.confirm_pushButton.setText(_translate("Form", "确定"))
        self.cancle_pushButton.setText(_translate("Form", "取消"))
