# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_info.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(657, 515)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.identifier_lineEdit = QtWidgets.QLineEdit(Form)
        self.identifier_lineEdit.setObjectName("identifier_lineEdit")
        self.horizontalLayout.addWidget(self.identifier_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.series_lineEdit = QtWidgets.QLineEdit(Form)
        self.series_lineEdit.setObjectName("series_lineEdit")
        self.horizontalLayout_2.addWidget(self.series_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.type_lineEdit = QtWidgets.QLineEdit(Form)
        self.type_lineEdit.setObjectName("type_lineEdit")
        self.horizontalLayout_3.addWidget(self.type_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 3, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.country_lineEdit = QtWidgets.QLineEdit(Form)
        self.country_lineEdit.setObjectName("country_lineEdit")
        self.horizontalLayout_8.addWidget(self.country_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 1, 0, 1, 2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.img_type_lineEdit = QtWidgets.QLineEdit(Form)
        self.img_type_lineEdit.setObjectName("img_type_lineEdit")
        self.horizontalLayout_10.addWidget(self.img_type_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 1, 2, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.video_director_lineEdit = QtWidgets.QLineEdit(Form)
        self.video_director_lineEdit.setObjectName("video_director_lineEdit")
        self.horizontalLayout_12.addWidget(self.video_director_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 1, 3, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.publish_time_lineEdit = QtWidgets.QLineEdit(Form)
        self.publish_time_lineEdit.setObjectName("publish_time_lineEdit")
        self.horizontalLayout_13.addWidget(self.publish_time_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 2, 0, 1, 2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.video_length_lineEdit = QtWidgets.QLineEdit(Form)
        self.video_length_lineEdit.setObjectName("video_length_lineEdit")
        self.horizontalLayout_14.addWidget(self.video_length_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 2, 2, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.video_zhizuoshang_lineEdit = QtWidgets.QLineEdit(Form)
        self.video_zhizuoshang_lineEdit.setObjectName("video_zhizuoshang_lineEdit")
        self.horizontalLayout_15.addWidget(self.video_zhizuoshang_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 2, 3, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        self.video_faxingshang_lineEdit = QtWidgets.QLineEdit(Form)
        self.video_faxingshang_lineEdit.setObjectName("video_faxingshang_lineEdit")
        self.horizontalLayout_16.addWidget(self.video_faxingshang_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_16, 3, 0, 1, 2)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        self.video_score_lineEdit = QtWidgets.QLineEdit(Form)
        self.video_score_lineEdit.setObjectName("video_score_lineEdit")
        self.horizontalLayout_17.addWidget(self.video_score_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_17, 3, 2, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_7.addWidget(self.label_19)
        self.like_stars_lineEdit = QtWidgets.QLineEdit(Form)
        self.like_stars_lineEdit.setObjectName("like_stars_lineEdit")
        self.horizontalLayout_7.addWidget(self.like_stars_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 3, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 1)
        self.video_path_lineEdit = QtWidgets.QLineEdit(Form)
        self.video_path_lineEdit.setObjectName("video_path_lineEdit")
        self.gridLayout_2.addWidget(self.video_path_lineEdit, 4, 1, 1, 3)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 5, 0, 1, 1)
        self.title_lineEdit = QtWidgets.QLineEdit(Form)
        self.title_lineEdit.setObjectName("title_lineEdit")
        self.gridLayout_2.addWidget(self.title_lineEdit, 5, 1, 1, 3)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 6, 0, 1, 1)
        self.video_name_local_lineEdit = QtWidgets.QLineEdit(Form)
        self.video_name_local_lineEdit.setObjectName("video_name_local_lineEdit")
        self.gridLayout_2.addWidget(self.video_name_local_lineEdit, 6, 1, 1, 3)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 4)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.intro_textEdit = QtWidgets.QTextEdit(Form)
        self.intro_textEdit.setMaximumSize(QtCore.QSize(16777215, 130))
        self.intro_textEdit.setObjectName("intro_textEdit")
        self.gridLayout.addWidget(self.intro_textEdit, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.actor_name_textEdit = QtWidgets.QTextEdit(Form)
        self.actor_name_textEdit.setMaximumSize(QtCore.QSize(16777215, 130))
        self.actor_name_textEdit.setObjectName("actor_name_textEdit")
        self.gridLayout.addWidget(self.actor_name_textEdit, 1, 3, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.pushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.custom_tag_textEdit = QtWidgets.QTextEdit(Form)
        self.custom_tag_textEdit.setMaximumSize(QtCore.QSize(16777215, 130))
        self.custom_tag_textEdit.setObjectName("custom_tag_textEdit")
        self.gridLayout.addWidget(self.custom_tag_textEdit, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 2, 2, 1, 1)
        self.video_tag_textEdit = QtWidgets.QTextEdit(Form)
        self.video_tag_textEdit.setMaximumSize(QtCore.QSize(16777215, 130))
        self.video_tag_textEdit.setObjectName("video_tag_textEdit")
        self.gridLayout.addWidget(self.video_tag_textEdit, 2, 3, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.save_pushButton = QtWidgets.QPushButton(Form)
        self.save_pushButton.setMaximumSize(QtCore.QSize(75, 23))
        self.save_pushButton.setObjectName("save_pushButton")
        self.horizontalLayout_4.addWidget(self.save_pushButton)
        self.cancel_pushButton = QtWidgets.QPushButton(Form)
        self.cancel_pushButton.setMaximumSize(QtCore.QSize(75, 23))
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.horizontalLayout_4.addWidget(self.cancel_pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "识别码  "))
        self.label_2.setText(_translate("Form", "系列    "))
        self.label_3.setText(_translate("Form", "类型    "))
        self.label_8.setText(_translate("Form", "国家    "))
        self.label_10.setText(_translate("Form", "封面类型"))
        self.label_12.setText(_translate("Form", "导演    "))
        self.label_13.setText(_translate("Form", "发行时间"))
        self.label_14.setText(_translate("Form", "影片时长"))
        self.label_15.setText(_translate("Form", "制作商  "))
        self.label_16.setText(_translate("Form", "发行商  "))
        self.label_17.setText(_translate("Form", "评分    "))
        self.label_19.setText(_translate("Form", "喜爱程度"))
        self.label_9.setText(_translate("Form", "影片路径"))
        self.label_11.setText(_translate("Form", "发行标题"))
        self.label_4.setText(_translate("Form", "本地名称"))
        self.label_7.setText(_translate("Form", "简介    "))
        self.label_5.setText(_translate("Form", "演员名称"))
        self.label_6.setText(_translate("Form", "自定标签"))
        self.pushButton.setText(_translate("Form", "编辑"))
        self.label_18.setText(_translate("Form", "官方标签"))
        self.save_pushButton.setText(_translate("Form", "保存"))
        self.cancel_pushButton.setText(_translate("Form", "取消"))
