# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_info.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(657, 515)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(12, 13, 630, 493))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.shibiema_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.shibiema_lineEdit.setObjectName("shibiema_lineEdit")
        self.horizontalLayout.addWidget(self.shibiema_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.xilie_lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.xilie_lineEdit_2.setObjectName("xilie_lineEdit_2")
        self.horizontalLayout_2.addWidget(self.xilie_lineEdit_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.leixing_lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.leixing_lineEdit_3.setObjectName("leixing_lineEdit_3")
        self.horizontalLayout_3.addWidget(self.leixing_lineEdit_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 3, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.guojia_lineEdit_8 = QtWidgets.QLineEdit(self.widget)
        self.guojia_lineEdit_8.setObjectName("guojia_lineEdit_8")
        self.horizontalLayout_8.addWidget(self.guojia_lineEdit_8)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 1, 0, 1, 2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.fengianleixing_lineEdit_10 = QtWidgets.QLineEdit(self.widget)
        self.fengianleixing_lineEdit_10.setObjectName("fengianleixing_lineEdit_10")
        self.horizontalLayout_10.addWidget(self.fengianleixing_lineEdit_10)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 1, 2, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.daoyan_lineEdit_12 = QtWidgets.QLineEdit(self.widget)
        self.daoyan_lineEdit_12.setObjectName("daoyan_lineEdit_12")
        self.horizontalLayout_12.addWidget(self.daoyan_lineEdit_12)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 1, 3, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.faxingshijian_lineEdit_13 = QtWidgets.QLineEdit(self.widget)
        self.faxingshijian_lineEdit_13.setObjectName("faxingshijian_lineEdit_13")
        self.horizontalLayout_13.addWidget(self.faxingshijian_lineEdit_13)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 2, 0, 1, 2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.yingpianshichang_lineEdit_14 = QtWidgets.QLineEdit(self.widget)
        self.yingpianshichang_lineEdit_14.setObjectName("yingpianshichang_lineEdit_14")
        self.horizontalLayout_14.addWidget(self.yingpianshichang_lineEdit_14)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 2, 2, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.zhizuoshang_lineEdit_15 = QtWidgets.QLineEdit(self.widget)
        self.zhizuoshang_lineEdit_15.setObjectName("zhizuoshang_lineEdit_15")
        self.horizontalLayout_15.addWidget(self.zhizuoshang_lineEdit_15)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 2, 3, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        self.faxingshang_lineEdit_16 = QtWidgets.QLineEdit(self.widget)
        self.faxingshang_lineEdit_16.setObjectName("faxingshang_lineEdit_16")
        self.horizontalLayout_16.addWidget(self.faxingshang_lineEdit_16)
        self.gridLayout_2.addLayout(self.horizontalLayout_16, 3, 0, 1, 2)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        self.pingfen_lineEdit_17 = QtWidgets.QLineEdit(self.widget)
        self.pingfen_lineEdit_17.setObjectName("pingfen_lineEdit_17")
        self.horizontalLayout_17.addWidget(self.pingfen_lineEdit_17)
        self.gridLayout_2.addLayout(self.horizontalLayout_17, 3, 2, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_7.addWidget(self.label_19)
        self.xiaichengdu_lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.xiaichengdu_lineEdit_7.setObjectName("xiaichengdu_lineEdit_7")
        self.horizontalLayout_7.addWidget(self.xiaichengdu_lineEdit_7)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 3, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 1)
        self.yingpianlujing_lineEdit_9 = QtWidgets.QLineEdit(self.widget)
        self.yingpianlujing_lineEdit_9.setObjectName("yingpianlujing_lineEdit_9")
        self.gridLayout_2.addWidget(self.yingpianlujing_lineEdit_9, 4, 1, 1, 3)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 5, 0, 1, 1)
        self.faxingbiaoti_lineEdit_11 = QtWidgets.QLineEdit(self.widget)
        self.faxingbiaoti_lineEdit_11.setObjectName("faxingbiaoti_lineEdit_11")
        self.gridLayout_2.addWidget(self.faxingbiaoti_lineEdit_11, 5, 1, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 6, 0, 1, 1)
        self.bendimingcheng_lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.bendimingcheng_lineEdit_4.setObjectName("bendimingcheng_lineEdit_4")
        self.gridLayout_2.addWidget(self.bendimingcheng_lineEdit_4, 6, 1, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.zidingyibiaoqian_textEdit_3 = QtWidgets.QTextEdit(self.widget)
        self.zidingyibiaoqian_textEdit_3.setMaximumSize(QtCore.QSize(16777215, 130))
        self.zidingyibiaoqian_textEdit_3.setObjectName("zidingyibiaoqian_textEdit_3")
        self.gridLayout.addWidget(self.zidingyibiaoqian_textEdit_3, 1, 1, 1, 1)
        self.yanyuan_textEdit_2 = QtWidgets.QTextEdit(self.widget)
        self.yanyuan_textEdit_2.setMaximumSize(QtCore.QSize(16777215, 130))
        self.yanyuan_textEdit_2.setObjectName("yanyuan_textEdit_2")
        self.gridLayout.addWidget(self.yanyuan_textEdit_2, 0, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 1, 2, 1, 1)
        self.guanfangbiaoqian_textEdit_4 = QtWidgets.QTextEdit(self.widget)
        self.guanfangbiaoqian_textEdit_4.setMaximumSize(QtCore.QSize(16777215, 130))
        self.guanfangbiaoqian_textEdit_4.setObjectName("guanfangbiaoqian_textEdit_4")
        self.gridLayout.addWidget(self.guanfangbiaoqian_textEdit_4, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.jianjie_textEdit = QtWidgets.QTextEdit(self.widget)
        self.jianjie_textEdit.setMaximumSize(QtCore.QSize(16777215, 130))
        self.jianjie_textEdit.setObjectName("jianjie_textEdit")
        self.gridLayout.addWidget(self.jianjie_textEdit, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "识别码  "))
        self.label_2.setText(_translate("Form", "系列    "))
        self.label_3.setText(_translate("Form", "类型    "))
        self.label_8.setText(_translate("Form", "国家    "))
        self.label_10.setText(_translate("Form", "封面类型"))
        self.label_12.setText(_translate("Form", "导演    "))
        self.label_13.setText(_translate("Form", "发行时间"))
        self.label_14.setText(_translate("Form", "影片时长"))
        self.label_15.setText(_translate("Form", "制作商  "))
        self.label_16.setText(_translate("Form", "发行商  "))
        self.label_17.setText(_translate("Form", "评分    "))
        self.label_19.setText(_translate("Form", "喜爱程度"))
        self.label_9.setText(_translate("Form", "影片路径"))
        self.label_11.setText(_translate("Form", "发行标题"))
        self.label_4.setText(_translate("Form", "本地名称"))
        self.label_18.setText(_translate("Form", "官方标签"))
        self.label_7.setText(_translate("Form", "简介    "))
        self.label_6.setText(_translate("Form", "自定标签"))
        self.label_5.setText(_translate("Form", "演员名称"))
        self.pushButton.setText(_translate("Form", "保存"))
        self.pushButton_2.setText(_translate("Form", "取消"))
