# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!
# 不能删
import resource_rc
from PyQt5 import QtCore, QtGui, QtWidgets

from ScrollWindow import ScrollWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.refresh_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_pushButton.setObjectName("refresh_pushButton")
        self.horizontalLayout.addWidget(self.refresh_pushButton)
        self.search_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.search_pushButton.setObjectName("search_pushButton")
        self.horizontalLayout.addWidget(self.search_pushButton)
        self.manage_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.manage_pushButton.setObjectName("manage_pushButton")
        self.horizontalLayout.addWidget(self.manage_pushButton)
        self.view_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.view_pushButton.setObjectName("view_pushButton")
        self.horizontalLayout.addWidget(self.view_pushButton)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(140, 20))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.like_order_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.like_order_radioButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.like_order_radioButton.setObjectName("like_order_radioButton")
        self.horizontalLayout_3.addWidget(self.like_order_radioButton)
        self.time_order_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.time_order_radioButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.time_order_radioButton.setChecked(True)
        self.time_order_radioButton.setObjectName("time_order_radioButton")
        self.horizontalLayout_3.addWidget(self.time_order_radioButton)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(100, 20))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.asc_order_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.asc_order_radioButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.asc_order_radioButton.setObjectName("asc_order_radioButton")
        self.horizontalLayout_4.addWidget(self.asc_order_radioButton)
        self.desc_order_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.desc_order_radioButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.desc_order_radioButton.setChecked(True)
        self.desc_order_radioButton.setObjectName("desc_order_radioButton")
        self.horizontalLayout_4.addWidget(self.desc_order_radioButton)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.scrollArea = ScrollWindow()
        # MainWindow.resize(1160, 700) 这句也要

        # self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        # self.scrollArea.setWidgetResizable(True)
        # self.scrollArea.setObjectName("scrollArea")
        # self.scrollAreaWidgetContents = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 911, 449))
        # self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.status_text_label = QtWidgets.QLabel(self.centralwidget)
        self.status_text_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.status_text_label.setObjectName("status_text_label")
        self.horizontalLayout_2.addWidget(self.status_text_label)
        self.last_page_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.last_page_pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.last_page_pushButton.setObjectName("last_page_pushButton")
        self.horizontalLayout_2.addWidget(self.last_page_pushButton)
        self.page_num_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.page_num_lineEdit.setMaximumSize(QtCore.QSize(24, 16777215))
        self.page_num_lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.page_num_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.page_num_lineEdit.setObjectName("page_num_lineEdit")
        self.horizontalLayout_2.addWidget(self.page_num_lineEdit)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(4, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.page_num_all_label = QtWidgets.QLabel(self.centralwidget)
        self.page_num_all_label.setMaximumSize(QtCore.QSize(24, 16777215))
        self.page_num_all_label.setAlignment(QtCore.Qt.AlignCenter)
        self.page_num_all_label.setObjectName("page_num_all_label")
        self.horizontalLayout_2.addWidget(self.page_num_all_label)
        self.next_page_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.next_page_pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.next_page_pushButton.setObjectName("next_page_pushButton")
        self.horizontalLayout_2.addWidget(self.next_page_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.openfile = QtWidgets.QAction(MainWindow)
        self.openfile.setObjectName("openfile")
        self.openfolder = QtWidgets.QAction(MainWindow)
        self.openfolder.setObjectName("openfolder")
        self.open_setting = QtWidgets.QAction(MainWindow)
        self.open_setting.setObjectName("open_setting")
        self.edit_tab = QtWidgets.QAction(MainWindow)
        self.edit_tab.setObjectName("edit_tab")
        self.downlowd_info = QtWidgets.QAction(MainWindow)
        self.downlowd_info.setObjectName("downlowd_info")
        self.downlowd_info_and_img = QtWidgets.QAction(MainWindow)
        self.downlowd_info_and_img.setObjectName("downlowd_info_and_img")
        self.downlowd_img = QtWidgets.QAction(MainWindow)
        self.downlowd_img.setObjectName("downlowd_img")
        self.open_file_action = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_file_action.setIcon(icon)
        self.open_file_action.setObjectName("open_file_action")
        self.open_folder_action = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_folder_action.setIcon(icon1)
        self.open_folder_action.setObjectName("open_folder_action")
        self.edit_tab_action = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/tag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_tab_action.setIcon(icon2)
        self.edit_tab_action.setObjectName("edit_tab_action")
        self.downlowd_infoaction_action = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/download_info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downlowd_infoaction_action.setIcon(icon3)
        self.downlowd_infoaction_action.setObjectName("downlowd_infoaction_action")
        self.downlowd_img_action = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/download_img.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downlowd_img_action.setIcon(icon4)
        self.downlowd_img_action.setObjectName("downlowd_img_action")
        self.open_setting_action = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_setting_action.setIcon(icon5)
        self.open_setting_action.setObjectName("open_setting_action")
        self.toolBar.addAction(self.open_file_action)
        self.toolBar.addAction(self.open_folder_action)
        self.toolBar.addAction(self.edit_tab_action)
        self.toolBar.addAction(self.downlowd_infoaction_action)
        self.toolBar.addAction(self.downlowd_img_action)
        self.toolBar.addAction(self.open_setting_action)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.refresh_pushButton.setText(_translate("MainWindow", "刷新"))
        self.search_pushButton.setText(_translate("MainWindow", "检索"))
        self.manage_pushButton.setText(_translate("MainWindow", "管理"))
        self.view_pushButton.setText(_translate("MainWindow", "视图"))
        self.like_order_radioButton.setText(_translate("MainWindow", "喜爱程度"))
        self.time_order_radioButton.setText(_translate("MainWindow", "导入时间"))
        self.asc_order_radioButton.setText(_translate("MainWindow", "正序"))
        self.desc_order_radioButton.setText(_translate("MainWindow", "倒序"))
        self.status_text_label.setText(_translate("MainWindow", "状态栏"))
        self.last_page_pushButton.setText(_translate("MainWindow", "上一页"))
        self.page_num_lineEdit.setText(_translate("MainWindow", "1"))
        self.label.setText(_translate("MainWindow", "/"))
        self.page_num_all_label.setText(_translate("MainWindow", "1"))
        self.next_page_pushButton.setText(_translate("MainWindow", "下一页"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.openfile.setText(_translate("MainWindow", "打开文件"))
        self.openfolder.setText(_translate("MainWindow", "打开文件夹"))
        self.open_setting.setText(_translate("MainWindow", "打开设置"))
        self.edit_tab.setText(_translate("MainWindow", "编辑标签"))
        self.downlowd_info.setText(_translate("MainWindow", "下载信息"))
        self.downlowd_info_and_img.setText(_translate("MainWindow", "下载信息和图片"))
        self.downlowd_img.setText(_translate("MainWindow", "下载图片(需先下载信息)"))
        self.open_file_action.setText(_translate("MainWindow", "打开文件"))
        self.open_file_action.setToolTip(_translate("MainWindow", "打开文件"))
        self.open_folder_action.setText(_translate("MainWindow", "打开文件夹"))
        self.open_folder_action.setToolTip(_translate("MainWindow", "打开文件夹"))
        self.edit_tab_action.setText(_translate("MainWindow", "编辑标签"))
        self.edit_tab_action.setToolTip(_translate("MainWindow", "编辑标签"))
        self.downlowd_infoaction_action.setText(_translate("MainWindow", "下载信息"))
        self.downlowd_infoaction_action.setToolTip(_translate("MainWindow", "下载信息"))
        self.downlowd_img_action.setText(_translate("MainWindow", "下载图片(需先下载信息)"))
        self.downlowd_img_action.setToolTip(_translate("MainWindow", "下载图片(需先下载信息)"))
        self.open_setting_action.setText(_translate("MainWindow", "打开设置"))
        self.open_setting_action.setToolTip(_translate("MainWindow", "打开设置"))
import resource_rc
